
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mesh-nodes

spec:
  replicas: 120

  selector:
    matchLabels:
      app: mesh-node

  template:
    metadata:
      labels:
        app: mesh-node

    spec:
      containers:
      - name: mesh-node
        image: mesh-node:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "15Mi"
            cpu: "10m"

        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
              
        - name: START_NODE
          value: "false"
        - name: LISTEN_PORT
          value: "5000"
        - name: NEXT_NODES
          value: "mesh-node.default.svc.cluster.local:5000"
  # Placeholder for neighbor logic
        ports:
        - containerPort: 5000
